index:
   path: /
   controller: App\Controller\ProductController::index

productCreate:
   path: /products/create
   controller: App\Controller\ProductController::create

productFind:
   path: /products/find/
   controller: App\Controller\ProductController::find

productShow:
   path: /products/show/{id}
   controller: App\Controller\ProductController::show

productDelete:
   path: /products/delete/{id}
   controller: App\Controller\ProductController::delete
